apiVersion: v1
kind: ServiceAccount
metadata:
  name: nginx
  labels:
    app.kubernetes.io/name: nginx
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: platform-breakfix
automountServiceAccountToken: false
