apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../kubernetes/shared
  - ../../../../kubernetes/ingress
  - ../../../../kubernetes/scheduling
  - ../../../../kubernetes/policies
  - ../../../../kubernetes/failures
  - storage
