apiVersion: v1
kind: ServiceAccount
metadata:
  name: podinfo
  labels:
    app.kubernetes.io/name: podinfo
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: platform-breakfix
automountServiceAccountToken: false
