apiVersion: v1
kind: ServiceAccount
metadata:
  name: curl
  labels:
    app.kubernetes.io/name: curl
    app.kubernetes.io/component: diagnostics
    app.kubernetes.io/part-of: platform-breakfix
automountServiceAccountToken: false
